project:
  type: website

website:
  title: "Women in STEM"
  sidebar:
    style: "docked"
    background: info
    tools:
      - icon: github
        href: https://github.com/lucaslopes/alunas
    contents:
      - href: sections/introduction.ipynb
      - sections/related.ipynb
      - section: "Materiais e Métodos"
        contents:
          - sections/data_raw.ipynb
          - sections/data_collect.ipynb
      - section: "Análise dos Dados e Resultados"
        contents:
          - sections/data_dict.qmd
          # - sections/data_aux.qmd
          - sections/data_provenance.ipynb
          - sections/data_fair.qmd
          - sections/data_inspect_and_results.ipynb
      - sections/conclusion.qmd

format:
  html:
    page-layout: full
    theme: cosmo
    css: styles.css
    toc: true


    